name: Build and Release
concurrency: release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        go-version: [1.22.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build application
        run: |
          make build-ci

      - name: Create zip file
        run: |
          zip justdeploy-linux-arm.zip bin/justdeploy-linux-arm
          zip justdeploy-linux-x86.zip bin/justdeploy-linux-x86
          zip justdeploy-darwin-arm.zip bin/justdeploy-darwin-arm
          zip justdeploy-darwin-x86.zip bin/justdeploy-darwin-x86

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            justdeploy-linux-arm.zip
            justdeploy-linux-x86.zip
            justdeploy-darwin-arm.zip
            justdeploy-darwin-x86.zip
