name: Build and Release
concurrency: release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build application
        run: |
          make

      - name: Create zip file
        run: |
          zip -r justdeploy.zip bin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: justdeploy.zip
